version: '3'
services:
  nsqlookupd:
    container_name: nsqlookupd
    restart: always
    image: nsqio/nsq
    command: /nsqlookupd --broadcast-address=127.0.0.1
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd1:
    container_name: nsqd1
    restart: always
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=127.0.0.1:4160 --broadcast-address=127.0.0.1 --tcp-address=:4150 --http-address=:4151
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqd2:
    container_name: nsqd2
    restart: always
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=127.0.0.1:4160 --broadcast-address=127.0.0.1 --tcp-address=:4250 --http-address=:4251
    depends_on:
      - nsqlookupd
    ports:
      - "4250:4250"
      - "4251:4251"
  nsqadmin:
    container_name: nsqadmin
    restart: always
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=127.0.0.1:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
